Repository PyLops/pylops, pull requests merged in 2022-04, with the labels that each got.

#357 feature: add option to choose dense solver to div
  pylops/LinearOperator.py
Labels: enhancement

#359 fix: handle case with dims scalar in Convolve1D
  pylops/signalprocessing/Convolve1D.py
Labels: bug

#367 Support for NDArray multiplication
  MIGRATION_V1_V2.md
  docs/source/api/others.rst
  examples/plot_bilinear.py
  examples/plot_nmo.py
  pylops/LinearOperator.py
  pylops/__init__.py
  pylops/avo/avo.py
  pylops/basicoperators/Symmetrize.py
  pylops/config.py
  pylops/optimization/leastsquares.py
  pylops/optimization/solver.py
  pylops/utils/decorators.py
  pytests/test_leastsquares.py
  pytests/test_linearoperator.py
  pytests/test_solver.py
Labels: enhancement, breaking
