Repository PyLops/pylops, pull requests merged in 2022-05, with the labels that each got.

#383 add Transform 2022 to tutorials
  README.md
Labels: documentation

#363 Class-based solvers
  MIGRATION_V1_V2.md
  docs/source/adding.rst
  docs/source/addingsolver.rst
  docs/source/api/index.rst
  docs/source/api/others.rst
  docs/source/index.rst
  examples/plot_bilinear.py
  examples/plot_causalintegration.py
  examples/plot_cgls.py
  examples/plot_ista.py
  examples/plot_linearregr.py
  examples/plot_regr.py
  examples/plot_sliding.py
  examples/plot_tvreg.py
  examples/plot_wavest.py
  pylops/LinearOperator.py
  pylops/__init__.py
  pylops/avo/poststack.py
  pylops/avo/prestack.py
  pylops/optimization/__init__.py
  pylops/optimization/basesolver.py
  pylops/optimization/basic.py
  pylops/optimization/basicc.py
  pylops/optimization/callback.py
  pylops/optimization/leastsquares.py
  pylops/optimization/leastsquaresc.py
  pylops/optimization/solver.py
  pylops/optimization/sparsity.py
  pylops/optimization/sparsityc.py
  pylops/waveeqprocessing/marchenko.py
  pylops/waveeqprocessing/mdd.py
  pylops/waveeqprocessing/seismicinterpolation.py
  pytests/test_chirpradon.py
  pytests/test_leastsquares.py
  pytests/test_radon.py
  pytests/test_seismicinterpolation.py
  pytests/test_solver.py
  pytests/test_sparsity.py
  tutorials/classsolvers.py
  tutorials/ctscan.py
  tutorials/deblending.py
  tutorials/deblurring.py
  tutorials/interpolation.py
  tutorials/lsm.py
  tutorials/radonfiltering.py
  tutorials/seismicinterpolation.py
  tutorials/solvers.py
Labels: enhancement, Core, breaking

#385 Refactor docs
  CONTRIBUTING.md
  MIGRATION_V1_V2.md
  Makefile
  README.md
  docs/source/addingsolver.rst
  docs/source/citing.rst
  docs/source/contributing.rst
  docs/source/extensions.rst
  docs/source/faq.rst
  docs/source/gpu.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/papers.rst
  docs/source/performance.rst
  docs/source/roadmap.rst
  pylops/optimization/basic.py
Labels: documentation

#388 Update README.md to link to stable and not latest
  README.md
Labels: documentation

#391 Refactor operators using super and reshaped
  pylops/avo/avo.py
  pylops/basicoperators/BlockDiag.py
  pylops/basicoperators/CausalIntegration.py
  pylops/basicoperators/Conj.py
  pylops/basicoperators/Diagonal.py
  pylops/basicoperators/FirstDerivative.py
  pylops/basicoperators/Flip.py
  pylops/basicoperators/FunctionOperator.py
  pylops/basicoperators/HStack.py
  pylops/basicoperators/Identity.py
  pylops/basicoperators/Imag.py
  pylops/basicoperators/Kronecker.py
  pylops/basicoperators/MatrixMult.py
  pylops/basicoperators/MemoizeOperator.py
  pylops/basicoperators/Pad.py
  pylops/basicoperators/Real.py
  pylops/basicoperators/Regression.py
  pylops/basicoperators/Restriction.py
  pylops/basicoperators/Roll.py
  pylops/basicoperators/SecondDerivative.py
  pylops/basicoperators/Spread.py
  pylops/basicoperators/Sum.py
  pylops/basicoperators/Transpose.py
  pylops/basicoperators/VStack.py
  pylops/basicoperators/Zero.py
  pylops/signalprocessing/Bilinear.py
  pylops/signalprocessing/ChirpRadon2D.py
  pylops/signalprocessing/ChirpRadon3D.py
  pylops/signalprocessing/Convolve1D.py
  pylops/signalprocessing/ConvolveND.py
  pylops/signalprocessing/DWT.py
  pylops/signalprocessing/DWT2D.py
  pylops/signalprocessing/FFT.py
  pylops/signalprocessing/FFT2D.py
  pylops/signalprocessing/FFTND.py
  pylops/signalprocessing/Fredholm1.py
  pylops/signalprocessing/Seislet.py
  pylops/signalprocessing/_BaseFFTs.py
  pylops/utils/decorators.py
Labels: Core
