Repository PyLops/pylops, pull requests merged in 2022-03, with the labels that each got.

#338 Update README.md
  README.md
Labels: documentation

#347 Implement `dimsd` for all operators with `dims`
  MIGRATION_V1_V2.md
  examples/plot_matrixmult.py
  pylops/avo/poststack.py
  pylops/avo/prestack.py
  pylops/basicoperators/CausalIntegration.py
  pylops/basicoperators/Conj.py
  pylops/basicoperators/Diagonal.py
  pylops/basicoperators/DirectionalDerivative.py
  pylops/basicoperators/FirstDerivative.py
  pylops/basicoperators/Flip.py
  pylops/basicoperators/Gradient.py
  pylops/basicoperators/Imag.py
  pylops/basicoperators/Laplacian.py
  pylops/basicoperators/MatrixMult.py
  pylops/basicoperators/Pad.py
  pylops/basicoperators/Real.py
  pylops/basicoperators/Restriction.py
  pylops/basicoperators/Roll.py
  pylops/basicoperators/SecondDerivative.py
  pylops/basicoperators/Spread.py
  pylops/basicoperators/Sum.py
  pylops/basicoperators/Symmetrize.py
  pylops/basicoperators/Transpose.py
  pylops/signalprocessing/Bilinear.py
  pylops/signalprocessing/Convolve1D.py
  pylops/signalprocessing/ConvolveND.py
  pylops/signalprocessing/DWT.py
  pylops/signalprocessing/DWT2D.py
  pylops/signalprocessing/FFT.py
  pylops/signalprocessing/FFT2D.py
  pylops/signalprocessing/FFTND.py
  pylops/signalprocessing/Interp.py
  pylops/signalprocessing/Patch2D.py
  pylops/signalprocessing/Seislet.py
  pylops/signalprocessing/Shift.py
  pylops/signalprocessing/Sliding1D.py
  pylops/signalprocessing/Sliding2D.py
  pylops/signalprocessing/Sliding3D.py
  pylops/signalprocessing/_BaseFFTs.py
  pylops/utils/_internal.py
  pytests/test_basicoperators.py
  pytests/test_ffts.py
Labels: breaking

#349 Convert all strings to fstrings when appropriate
  examples/plot_cgls.py
  examples/plot_diagonal.py
  examples/plot_identity.py
  examples/plot_linearregr.py
  examples/plot_matrixmult.py
  examples/plot_pad.py
  examples/plot_regr.py
  examples/plot_stacking.py
  examples/plot_zero.py
  pylops/optimization/solver.py
  pylops/optimization/sparsity.py
  pylops/signalprocessing/ChirpRadon3D.py
  pylops/signalprocessing/DWT.py
  pylops/signalprocessing/DWT2D.py
  pylops/signalprocessing/FFT.py
  pylops/signalprocessing/Patch2D.py
  pylops/signalprocessing/Sliding1D.py
  pylops/signalprocessing/Sliding2D.py
  pylops/signalprocessing/Sliding3D.py
  pylops/utils/multiproc.py
  pylops/utils/tapers.py
  pylops/waveeqprocessing/lsm.py
  pylops/waveeqprocessing/mdd.py
  pylops/waveeqprocessing/seismicinterpolation.py
  pytests/test_causalintegration.py
  pytests/test_ffts.py
  pytests/test_functionoperator.py
  pytests/test_interpolation.py
  pytests/test_leastsquares.py
  pytests/test_oneway.py
  pytests/test_prestack.py
  tutorials/dottest.py
  tutorials/linearoperator.py
  tutorials/realcomplex.py
Labels: enhancement
